#### register a product 

POST http://localhost:3000/vendor/addNewProduct
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIrOTE4MTY4MjYwMzEzIiwiaWF0IjoxNjc2MDk5OTk4LCJleHAiOjE2NzYxMDM1OTh9.iVf04513flhdUb5ENXywMzw_8s0nvfNPCLl0zUMrjBU

{
    "title": "Nokia P30 lumia cover",
    "price": "499",
    "MRP": 500,
    "description":"Best High Quality Nokia P30 lumia cover",
    "images": ["image1.jpg", "image2.jpg"],
 "vendorID":"+918168260313",
 "location": {
    "type": "Point",
    "coordinates": [29.3,72.2]
  }
}

### Add review

POST  http://localhost:3000/products/addReview
content-type:application/json

{
  "content": "Awesome, worth buying",
  "productId": "63cf981774325b6318e8a017",
  "username": "Shubham Panchal",
  "rating": 4
}

### Get product with reviews

POST http://localhost:3000/products/getProductWithReviewsWithId
content-type:application/json

{
  "product":{
    "_id":"63cf981774325b6318e8a017"
  }
}


### POST Seller

POST  http://localhost:3000/vendor/register
content-type:application/json

{
  "name": "A1 mobile accesories",
  "phoneNumber": 8168260313,
  "category": "mobile accessories",
  "city": "Karnal",
  "address": "new char gali no. 20",
  "unwantedField":"Unwanted field"
  }  


##### Login 

POST  http://localhost:3000/auth/sendOtp
content-type:application/json

{
  "phoneNumber": "+918168260313"
}  
  
##### Verify

POST  http://localhost:3000/user/login
content-type:application/json

{
  "phoneNumber": "+918168260313",
  "otp":"368372",
  "roles":["customer"]
}  

### visiting a protected route

Get http://localhost:3000/auth/dashboard/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIrOTE4MTY4MjYwMzEzIiwidXNlclJvbGUiOlsiY3VzdG9tZXIiXSwiaWF0IjoxNjg5Nzc1MDI5LCJleHAiOjE2ODk3Nzg2Mjl9.7816tHTvP66IkaoMJij7zeVmjjwQl6Udn8mHlPpXq78
### visiting a protected route in of some other module 

Get http://localhost:3000/vendor/sensitive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIrOTE4MTY4MjYwMzEzIiwidXNlclJvbGUiOlsiY3VzdG9tZXIiXSwiaWF0IjoxNjg5Nzc1MDI5LCJleHAiOjE2ODk3Nzg2Mjl9.NG5MXq-4PWglyVCMC69ql477lYEe47AF1DONHQ2H6Y
#### Find all uploaded products of vendor

# when one uses query object for this same task the +, digit i don't actually get sent but an empty space on the place of it.  

POST  http://localhost:3000/vendor/retrieveAllProducts
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIrOTE4MTY4MjYwMzEzIiwiaWF0IjoxNjc2MDk5OTk4LCJleHAiOjE2NzYxMDM1OTh9.iVf04513flhdUb5ENXywMzw_8s0nvfNPCLl0zUMrjBU

{
  "vendorID":"+918168260313"
}


#### Vendor Update a product 
PATCH   http://localhost:3000/vendor/updateProduct/+918168260313
content-type:application/json

{
  "title":"Non-Yellowing Hard Nothing Phone(1) Cover"
}